name: Create Github Release
description: Create a Github Release
branding:
  icon: box
  color: white
inputs:
  tag:
    description: Tag to create release
    required: true
    default: ${{ github.ref_name }}
  name:
    description: Release name
    required: false
  body:
    description: Release body
    required: false
  body-file:
    description: Filename to the release body content
    required: false
  generate-release-notes:
    description: |-
      Automatically generate release notes. Set to `true` to generate release notes from the latest release. Valid values: `true`, `false` or tag
    required: true
    default: "true"
  prerelease:
    description: Mark release as prerelease
    required: false
    default: "false"
  files:
    description: Files to attach to the release. One file per line
    required: false
  discussion-category:
    description: Github Discussion category
    required: false
  dry-run:
    description: Dry run
    required: false
    default: "false"
  token:
    description: Github Token
    required: true
    default: ${{ github.token }}
outputs:
  id:
    description: Release ID
  url:
    description: Release URL
  name:
    description: Release Name
  body:
    description: Release Body
  tag:
    description: Release Tag
  prerelease:
    description: Release Prerelease
  json:
    description: Release as JSON
runs:
  using: node20
  main: dist/index.js
